name : Docker Image CI
on :
  push :
    branches :
      - master
jobs :
  build :
    runs-on : ubuntu-latest
    steps :
    - name: Checkout
      uses: actions/checkout@v2
    - name : Build at The Docker Image
      run : |
        docker login --username=${{ secrets.DOCKER_HUB_USER }} --password=${{ secrets.DOCKER_HUB_PWD }}
        docker build -t strato190/go-ktest-app:0.0.1 .
        docker push strato190/go-ktest-app
        docker logout